version: '3.8'

services:
 mammamia:
    build: https://github.com/xfilex5/MammaMia.git#main
    container_name: mammamia
     env_file:
       - ./xfilex5/.env
    restart: unless-stopped 
    ports:
      - "8081:8081"
